# Generated by Django 6.0.7 on 2026-08-04 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='household',
            options={'ordering': ['name', 'created_at'], 'verbose_name': 'household', 'verbose_name_plural': 'households'},
        ),
        migrations.CreateModel(
            name='HouseholdMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member'), ('guest', 'Guest'), ('administrator', 'Administrator')], default='member', max_length=20)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='households.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'household membership',
                'verbose_name_plural': 'household memberships',
                'ordering': ['household', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('household', 'user'), name='unique_household_membership')],
            },
        ),
    ]
