# Generated by Django 6.0.7 on 2026-08-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_alter_household_options_householdmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('administrator', 'Administrator'), ('member', 'Member'), ('guest', 'Guest')], default='member', max_length=20),
        ),
    ]
