# Generated by Django 6.0.7 on 2026-08-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0003_alter_householdmembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
