# Generated by Django 6.0.7 on 2026-08-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("households", "0005_householdinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="householdinvitation",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="householdinvitation",
            name="expire_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="householdinvitation",
            name="last_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="householdinvitation",
            name="token_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
