# Generated by Django 6.0.7 on 2026-08-24 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("households", "0006_householdinvitation_accepted_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="householdinvitation",
            old_name="expire_at",
            new_name="expires_at",
        ),
    ]
