# Generated by Django 6.0.7 on 2026-08-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("households", "0007_rename_expire_at_householdinvitation_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="household",
            name="household_type",
            field=models.CharField(
                choices=[
                    ("primary", "Primary Household"),
                    ("vacation", "Vacation Home"),
                    ("rental", "Rental Property"),
                    ("other", "Other"),
                ],
                default="primary",
                max_length=20,
            ),
        ),
    ]
